### ISSUE TITLE
Invalid virtual host reference "secure" error when using the -v option

### ISSUE THREAD

**Issue by dmryn** [apigee-internal/microgateway#135]
We are seeing an error in version 2.4.6 and the latest beta when running the following configure command with the option -v to specify a virtualhost name. In our case our secure virtual host is named default. This seems to be ignoring the -v option.

Please note this does work in prior versions that I've used such as 2.3.5 or below. Also worth mentioning we're running on-prem so using the "private configure".

**Command**
edgemicro private configure -u "myemail@somedomain.com" -o myorg -e test -r https://apis.somedomain.com -m https://edgemgmt-api.somedomain.com -v default

**Error**
current nodejs version is v8.3.0
current edgemicro version is 2.4.6
password:
delete cache config
deleted /Users/n0054122/.edgemicro/internal-sandbox-config.yaml
init config
file doesn't exist, setting up
configuring edgemicro internal proxy
deploying edgemicro internal proxy
deploying  edgemicro-auth  app
Give me a minute or two... this can take a while...
Error: Invalid virtual host reference secure. Context Revision:1;APIProxy:edgemicro-auth;Organization:internal;Environment:sandbox
    at Request._callback (/usr/local/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/deployproxy.js:655:12)
    at Request.self.callback (/usr/local/lib/node_modules/edgemicro/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/edgemicro/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/edgemicro/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)`

**Comment by srinandan** [comment]
Yeah. I think we should fix this. The assumption we made is that the edgemicro-auth proxy will always be over TLS (or secure virtual host). This may not always be true for OPDK installs. 

For now, if you go to the Edge UI, you will see the proxy in an undeployed state. Manually deploy it to default VH. Then run configure again. It should work fine.

**Comment by dmryn** [comment]
Are there plans to fix this as well in the next release?

**Comment by srinandan** [comment]
Fixed in v.2.5.7
