### ISSUE TITLE
upgradeauth error can't find proxy base directory

### ISSUE THREAD

**Issue by WWitman** [apigee-internal/microgateway#138]
I have v2.5.4 installed, but tried running "edgemicro upgradeauth" to see if what it does. I got the following error where it seems to be looking in the wrong place for the edgemicro-auth proxy in my installation. Proxy is actually here: /Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/microgateway-edgeauth

edgemicro upgradeauth -o docs -e test -u willwitman@google.com
current nodejs version is v6.9.1
current edgemicro version is 2.5.4
password:
Error: Proxy base directory /Users/willwitman/npm/lib/node_modules/edgemicro/cli/lib/node_modules/microgateway-edgeauth does not exist
    at getDeploymentInfo (/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/deployproxy.js:162:10)
    at /Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/deployproxy.js:88:7
    at /Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/Users/willwitman/npm/lib/node_modules/edgemicro/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by srinandan** [comment]
i confirm a bug. fixing it now.

**Comment by srinandan** [comment]
Fixed in v.2.5.7
