### ISSUE TITLE
Error uploading resource: 400 during first time setup

### ISSUE THREAD

**Issue by incubus8** [apigee-internal/microgateway#153]
Error during first time setup.

```shell
$ edgemicro configure  -o rhezas -u XXXXXXXXXX@gmail.com -p XXXXX -e test -d
current nodejs version is v8.9.1
current edgemicro version is 2.5.8
file doesn't exist, setting up
listdeployments: {"organization":"rhezas","environment":"test","baseuri":"https://api.enterprise.apigee.com","debug":true,"username":"rheza.satria.ta@gmail.com","password":{},"asynclimit":4}
Going to invoke "https://api.enterprise.apigee.com/v1/o/rhezas/e/test/deployments"
List of deployed APIs: {"aPIProxy":[{"name":"Pet","revision":[{"configuration":{"basePath":"/","steps":[]},"name":"1","server":[{"status":"deployed","type":["message-processor"],"uUID":"8d311ffa-c742-42ca-8707-3024c4309555"},{"status":"deployed","type":["message-processor"],"uUID":"c8d88d3b-b847-4c9e-a095-d69c3e126b0b"},{"status":"deployed","type":["router"],"uUID":"128875b4-2e2c-4803-ab44-ef03c2b27145"},{"status":"deployed","type":["router"],"uUID":"d1947fa3-0689-47b5-abef-d70e6e19e815"},{"status":"deployed","type":["router"],"uUID":"df2fbeec-b028-4d3c-bb96-a827b235166e"}],"state":"deployed"}]}],"name":"test","organization":"rhezas"}
All done
Give me a minute or two... this can take a while...
deployproxy: {"organization":"rhezas","environments":"test","baseuri":"https://api.enterprise.apigee.com","debug":true,"verbose":true,"api":"edgemicro-auth","directory":"/Users/angel/.edgemicro/tmp-668296YIxw9wBqh24","virtualhosts":"default,secure","username":"rheza.satria.ta@gmail.com","password":{},"asynclimit":4}
Resolve NPM modules = false
Going to create revision NaN of API edgemicro-auth
Using /Users/angel/.edgemicro/tmp-668296YIxw9wBqh24/apiproxy/edgemicro-auth.xml as the root file
Calling https://api.enterprise.apigee.com/v1/o/rhezas/apis?action=import&validate=false&name=edgemicro-auth
Creating revision NaN of API edgemicro-auth
Uploading java resource micro-gateway-products-javacallout-2.0.0.jar
Uploading jsc resource generate-verify-jwt.js
Uploading jsc resource send-public-key.js
Uploading jsc resource set-jwt-variables.js
Error: Error uploading resource: 400
    at handleUploadResult (/Users/angel/.nvm/versions/node/v8.9.1/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/deployproxy.js:342:14)
    at Request._callback (/Users/angel/.nvm/versions/node/v8.9.1/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/deployproxy.js:325:9)
    at Request.self.callback (/Users/angel/.nvm/versions/node/v8.9.1/lib/node_modules/edgemicro/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/angel/.nvm/versions/node/v8.9.1/lib/node_modules/edgemicro/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/angel/.nvm/versions/node/v8.9.1/lib/node_modules/edgemicro/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by srinandan** [comment]
Sorry for the late response. Is this still an issue?
