### ISSUE TITLE
Config reload throws exception

### ISSUE THREAD

**Issue by philschleier** [apigee-internal/microgateway#154]
MGW version: 2.5.8 running in Docker

```
Reload completed
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:606:16)
    at Worker.send (internal/cluster/worker.js:40:28)
    at disconnectAndShutdownWorker (/usr/local/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:148:16)
    at EventEmitter.replaceAndTerminateWorker (/usr/local/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:121:5)
    at EventEmitter.emit (events.js:159:13)
    at emit (/usr/local/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:56:15)
    at EventEmitter.emitWorkerDisconnect (/usr/local/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:169:5)
    at EventEmitter.emit (events.js:159:13)
    at ChildProcess.worker.process.once (internal/cluster/master.js:207:13)
    at Object.onceWrapper (events.js:254:19)
    at ChildProcess.emit (events.js:159:13)
    at finish (internal/child_process.js:775:14)
    at process._tickCallback (internal/process/next_tick.js:150:11)
  microgateway Caught Unhandled Exception: +633ms
```

Exception seems to occur because of worker.send in cli/lib/cluster-reload.js:150.
`
try {
  worker.send({cmd: 'disconnect'});
  worker.disconnect();
} catch (e) {
}
`

To make the exception visible we changed cli/lib/gateway.js:136 to include an actual error:
`process.on('uncaughtException', (err) => {`

Not sure how to fix the actual exception though.

**Comment by philschleier** [comment]
Update: Seems a new issue on Node.js 9.x - works with 8.9.4 LTS

**Comment by srinandan** [comment]
Thanks for letting me know. I will try and reproduce the issue.

**Comment by srinandan** [comment]
I am not able to reproduce the issue.
