### ISSUE TITLE
ECONNRESET on requests with headers too large

### ISSUE THREAD

**Issue by victoranaylton** [apigee-internal/microgateway#171]
Hi,

I have an EMG **(2.5.16)** in front of an application running on a tomcat server.
Sometimes, when EMG receive a request with a header too large *(larger than 8k which is the default header limit on tomcat)*, EMG seems to dive into a race condition where sometimes will answer a `400 HTTP status` (returned from tomcat) and sometimes it will answer a `502 HTTP` status with an `ECCONRESET` error message.

Here's the log of a successful request:
```
info sourceRequest m=GET, u=/ping, h=***, r=*** i=aa007400-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:22:44 GMT spikearrest SpikeArrest check: undefined
Tue, 29 May 2018 19:22:44 GMT spikearrest applying: {"weight":1,"key":"_default"} to bucket: {"buffer":[],"nextWindow":1527621764751}
info targetRequest m=GET, u=/ping, h=localhost:8080, i=aa007400-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:22:44 GMT gateway:main targetRequest aa007400-6375-11e8-bdff-61a210c9460b GET localhost 8080 /ping
Tue, 29 May 2018 19:22:44 GMT gateway:main plugin spikearrest does not provide handler function for end_request
Tue, 29 May 2018 19:22:44 GMT gateway:main targetResponse aa007400-6375-11e8-bdff-61a210c9460b 400
info targetResponse s=400, d=7, i=aa007400-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:22:44 GMT gateway:main plugin spikearrest does not provide handler function for response
Tue, 29 May 2018 19:22:44 GMT gateway:main sourceRequest close
Tue, 29 May 2018 19:22:44 GMT gateway:main [ null, null, null, null ]
Tue, 29 May 2018 19:22:44 GMT gateway:main targetResponse close aa007400-6375-11e8-bdff-61a210c9460b
info res close s=400, d=8, i=aa007400-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:22:44 GMT gateway:main plugin spikearrest does not provide handler function for end_response
Tue, 29 May 2018 19:22:45 GMT analytics flushing 1 records. 0 records remaining
```

You can see that the target response will be a HTTP status 400 and this response will be returned to the EMG's client.

Here's the log of a request with the ECCONRESET error:

```
info sourceRequest m=GET, u=/ping, h=***, r=***, i=c44882d0-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:23:29 GMT spikearrest SpikeArrest check: undefined
Tue, 29 May 2018 19:23:29 GMT spikearrest applying: {"weight":1,"key":"_default"} to bucket: {"buffer":[],"nextWindow":1527621804751}
Tue, 29 May 2018 19:23:29 GMT gateway:main targetRequest c44882d0-6375-11e8-bdff-61a210c9460b GET localhost 8080 /ping
Tue, 29 May 2018 19:23:29 GMT gateway:main plugin spikearrest does not provide handler function for end_request
info targetRequest m=GET, u=/ping, h=localhost:8080, i=c44882d0-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:23:29 GMT gateway:main targetResponse c44882d0-6375-11e8-bdff-61a210c9460b 400
info targetResponse s=400, d=15, i=c44882d0-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:23:29 GMT gateway:main targetRequest error c44882d0-6375-11e8-bdff-61a210c9460b Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
warn targetRequest error m=undefined, u=undefined, h=, r=:0, d=16, i=c44882d0-6375-11e8-bdff-61a210c9460b, name=Error, message=read ECONNRESET, code=ECONNRESET, stack=Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
Tue, 29 May 2018 19:23:29 GMT gateway:main plugin analytics does not provide handler function for error_request
Tue, 29 May 2018 19:23:29 GMT gateway:main plugin spikearrest does not provide handler function for response
Tue, 29 May 2018 19:23:29 GMT gateway:main plugin spikearrest does not provide handler function for error_request
Tue, 29 May 2018 19:23:29 GMT gateway:main sourceRequest close
Tue, 29 May 2018 19:23:29 GMT gateway:main [ null, null, null, null ]
Tue, 29 May 2018 19:23:29 GMT gateway:main targetResponse close c44882d0-6375-11e8-bdff-61a210c9460b
info res close s=400, d=17, i=c44882d0-6375-11e8-bdff-61a210c9460b
Tue, 29 May 2018 19:23:29 GMT gateway:errors Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
error m=GET, u=/ping, h=***, r=***, s=502, name=Error, message=read ECONNRESET, code=ECONNRESET, stack=Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
Tue, 29 May 2018 19:23:29 GMT gateway:main plugin spikearrest does not provide handler function for end_response
Tue, 29 May 2018 19:23:29 GMT gateway:main Error: Callback was already called.
    at /app/async/lib/async.js:43:36
    at /app/async/lib/async.js:723:17
    at /app/async/lib/async.js:167:37
    at /app/microgateway-core/lib/plugins-middleware.js:73:37
    at /app/microgateway-core/lib/plugins-middleware.js:334:21
    at /app/microgateway-core/lib/plugins-middleware.js:442:24
    at /app/async/lib/async.js:1154:26
    at /app/async/lib/async.js:380:13
    at /app/async/lib/async.js:52:16
    at /app/async/lib/async.js:269:32
    at /app/async/lib/async.js:44:16
    at /app/async/lib/async.js:377:17
    at /app/async/lib/async.js:1150:21
    at /app/async/lib/async.js:167:37
    at fx (/app/microgateway-core/lib/plugins-middleware.js:507:25)
    at onend_response (/app/microgateway-plugins/analytics/index.js:71:7)
Tue, 29 May 2018 19:23:29 GMT analytics flushing 1 records. 0 records remaining.
```

by the logs above, i can undestand that:

1. EMG receives the request and send it to the target
2. Tomcat rejects the request due to the large header
3. EMG receives the response from the target but it seems to keep with the request active
4. Tomcat closes the connection and then EMG receives a `Request Error`
5. EMG overrides the first response from the target (400 status) by the 502 status and send it back to the client.

Maybe the tomcat on the target rejects the request even without receiving the whole request, in this case EMG is still processing the request and sending to the target when receive the response. When the connection is closed we got the error.

If this is true, shouldn't EMG close the requests after receiving a response from the target?

**Comment by srinandan** [comment]
this is addressed in 2.5.20-beta.
