### ISSUE TITLE
paramenter -t and -d is not working for cli comand edgemicro private configure

### ISSUE THREAD

**Issue by Kittiman** [apigee-internal/microgateway#197]
According to documentation https://docs.apigee.com/api-platform/microgateway/2.5.x/cli-reference-edge-microgateway section Configuring Edge Microgateway for Apigee Edge Private Cloud it should be possible to use a OAuth token for authentication instead of username/password.

But when using an error message: **_unknown option `-t'_** is thrown.

Using version: 2.5.26

**Comment by anshul07** [comment]
@srinandan  we are also facing a similar issue in the public cloud. We are getting 401 when we pass the token to edgemicro configure command. 

Sample command:
`edgemicro configure -o orgname -e environment -t <oauth token>`
`current nodejs version is v6.9.2
current edgemicro version is 2.5.27
file doesn't exist, setting up
Error: HTTP error 401
    at Request._callback (/Users/anshula/.nvm/versions/node/v6.9.2/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/listdeployments.js:93:12)
    at Request.self.callback (/Users/anshula/.nvm/versions/node/v6.9.2/lib/node_modules/edgemicro/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
`
edgemicro version: 2.5.27

**Comment by Kittiman** [comment]
Hi,

I did look in to the code of version 2.5.27-beta and there are some functions missing the if statemen when a token is provided and not username/password

**Comment by srinandan** [comment]
Can you please try with 2.5.28? I believe this issue is now addressed.

**Comment by smitarani** [comment]
Even with 2.5.28 having the same issue. Please suggest if someone find the solution 
Error:
current nodejs version is v6.9.1
current edgemicro version is 2.5.28
file doesn't exist, setting up
Error: HTTP error 401
    at Request._callback (/root/.nvm/versions/node/v6.9.1/lib/node_modules/edgemicro/node_modules/apigeetool/lib/commands/listdeployments.js:93:12)
    at Request.self.callback (/root/.nvm/versions/node/v6.9.1/lib/node_modules/edgemicro/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/.nvm/versions/node/v6.9.1/lib/node_modules/edgemicro/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v6.9.1/lib/node_modules/edgemicro/node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
