### ISSUE TITLE
microgateway docker container is not starting - [microgateway gateway] Error: listen EIO: i/o error /opt/apigee/edgemicro.sock

### ISSUE THREAD

**Issue by pt-bhavsar** [apigee-internal/microgateway#288]
Microgateway container is not starting. Below is the generated log:
edgemicro-docker_1   | Log Location: [ /opt/apigee/logs/edgemicro.log ]
edgemicro-docker_1   | SIGTERM delay : [  ]
edgemicro-docker_1   | base64: invalid input
edgemicro-docker_1   | Overriding port to 8000
edgemicro-docker_1   | cd /opt/apigee && edgemicro start -o xxxxx -e dev -k xxxxxxxxxxxxxxxxxx -s xxxxxxxxxxxxxxxxxx-p 1 -d /opt/apigee/plugins &
edgemicro-docker_1   | 2020-05-19T23:48:10.795Z [18] [microgateway edgemicro] current nodejs version is v12.16.3
edgemicro-docker_1   | 2020-05-19T23:48:10.798Z [18] [microgateway edgemicro] current edgemicro version is 3.1.4
helloworldservice_1  | Running on http://0.0.0.0:8080
edgemicro-docker_1   | 2020-05-19T23:48:13.752Z [18] [microgateway-config network] jwt_public_key download from https://xxxxx.com/edgemicro-auth/publicKey returned 200 OK
edgemicro-docker_1   | 2020-05-19T23:48:14.000Z [18] [microgateway-config network] products download from https://xxxxx.com/edgemicro-auth/products returned 200 OK
edgemicro-docker_1   | 2020-05-19T23:48:14.943Z [18] [microgateway-config network] config download from https://edgemicroservices.apigee.net/edgemicro/bootstrap/organization/xxxx/environment/dev returned 200 OK
edgemicro-docker_1   | 2020-05-19T23:48:15.147Z [18] [microgateway gateway] PROCESS PID : 18
edgemicro-docker_1   | 2020-05-19T23:48:15.170Z [18] [microgateway gateway] Error: listen EIO: i/o error /opt/apigee/edgemicro.sock
edgemicro-docker_1   |     at Server.setupListenHandle [as _listen2] (net.js:1296:21)
edgemicro-docker_1   |     at listenInCluster (net.js:1361:12)
edgemicro-docker_1   |     at Server.listen (net.js:1460:5)
edgemicro-docker_1   |     at startGateway (/usr/local/lib/node_modules/edgemicro/cli/lib/gateway.js:141:16)
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/lib/network.js:197:13
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/lib/network.js:533:9
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/async/lib/async.js:726:13
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/async/lib/async.js:52:16
edgemicro-docker_1   |     at done (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/async/lib/async.js:246:17)
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/async/lib/async.js:44:16
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/async/lib/async.js:723:17
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/async/lib/async.js:167:37
edgemicro-docker_1   |     at _loadStatus (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/lib/network.js:582:9)
edgemicro-docker_1   |     at Request._callback (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/lib/network.js:328:29)
edgemicro-docker_1   |     at Request.self.callback (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/request/request.js:185:22)
edgemicro-docker_1   |     at Request.emit (events.js:310:20)
edgemicro-docker_1   |     at Request.<anonymous> (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/request/request.js:1161:10)
edgemicro-docker_1   |     at Request.emit (events.js:310:20)
edgemicro-docker_1   |     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-config/node_modules/request/request.js:1083:12)
edgemicro-docker_1   |     at Object.onceWrapper (events.js:416:28)
edgemicro-docker_1   |     at IncomingMessage.emit (events.js:322:22)
edgemicro-docker_1   |     at endReadableNT (_stream_readable.js:1187:12) {
edgemicro-docker_1   |   code: 'EIO',
edgemicro-docker_1   |   errno: 'EIO',
edgemicro-docker_1   |   syscall: 'listen',
edgemicro-docker_1   |   address: '/opt/apigee/edgemicro.sock',
edgemicro-docker_1   |   port: -1
edgemicro-docker_1   | }
edgemicro-docker_1   | 2020-05-19T23:48:15.177Z [18] [microgateway gateway] Removing the socket file as part of cleanup
edgemicro-docker_1   | 2020-05-19T23:48:16.518Z [1] [microgateway plugins] using pluginDir
edgemicro-docker_1   | 2020-05-19T23:48:16.525Z [1] [microgateway plugins] using plugin dir /opt/apigee/plugins
edgemicro-docker_1   | events.js:287
edgemicro-docker_1   |       throw er; // Unhandled 'error' event
edgemicro-docker_1   |       ^
edgemicro-docker_1   |
edgemicro-docker_1   | Error: write EPIPE
edgemicro-docker_1   |     at process.target._send (internal/child_process.js:806:20)
edgemicro-docker_1   |     at process.target.send (internal/child_process.js:677:19)
edgemicro-docker_1   |     at writeLog (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/logging.js:132:17)
edgemicro-docker_1   |     at Object.info (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/logging.js:146:14)
edgemicro-docker_1   |     at Plugins.loadPlugin (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/plugins.js:64:12)
edgemicro-docker_1   |     at Gateway.addPlugin (/usr/local/lib/node_modules/edgemicro/node_modules/microgateway-core/index.js:56:37)
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/lib/plugins.js:59:13
edgemicro-docker_1   |     at Array.forEach (<anonymous>)
edgemicro-docker_1   |     at Plugins.loadPlugins (/usr/local/lib/node_modules/edgemicro/lib/plugins.js:46:12)
edgemicro-docker_1   |     at init (/usr/local/lib/node_modules/edgemicro/lib/gateway.js:12:49)
edgemicro-docker_1   |     at Agent.start (/usr/local/lib/node_modules/edgemicro/lib/server.js:64:26)
edgemicro-docker_1   |     at startServer (/usr/local/lib/node_modules/edgemicro/lib/agent-config.js:32:9)
edgemicro-docker_1   |     at /usr/local/lib/node_modules/edgemicro/lib/agent-config.js:24:7
edgemicro-docker_1   |     at suppressedCallback (fs.js:211:5)
edgemicro-docker_1   |     at FSReqCallback.oncomplete (fs.js:155:23)
edgemicro-docker_1   | Emitted 'error' event on Worker instance at:
edgemicro-docker_1   |     at process.<anonymous> (internal/cluster/worker.js:29:12)
edgemicro-docker_1   |     at process.emit (events.js:310:20)
edgemicro-docker_1   |     at internal/child_process.js:810:39
edgemicro-docker_1   |     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
edgemicro-docker_1   |   errno: 'EPIPE',
edgemicro-docker_1   |   code: 'EPIPE',
edgemicro-docker_1   |   syscall: 'write'
edgemicro-docker_1   | }

**Comment by pt-bhavsar** [comment]
@keyurkarnik @rajeshm7910 @srinandan could you please take a look?
