### ISSUE TITLE
npm install -g edgemicro@2.0.11 leads to missing dependency "portastic"

### ISSUE THREAD

**Issue by asnowfix** [apigee-internal/microgateway#45]
Trying to install the latest stable (pre-beta) edgemicro leads to a missing `portastic` dependency.

```
$ sudo npm install -g edgemicro@2.0.11
[sudo] password for kowalskif: 
npm WARN engine edgemicro@2.0.11: wanted: {"node":">=5.0.0 <6.0.0"} (current: {"node":"4.4.3","npm":"2.15.1"})
 
> dtrace-provider@0.6.0 install /usr/local/node-v4.4.3-linux-x64/lib/node_modules/edgemicro/node_modules/dtrace-provider
> node scripts/install.js

/usr/local/node-v4.4.3-linux-x64/bin/edgemicro -> /usr/local/node-v4.4.3-linux-x64/lib/node_modules/edgemicro/cli/edgemicro
edgemicro@2.0.11 /usr/local/node-v4.4.3-linux-x64/lib/node_modules/edgemicro
[...]
├── xmlbuilder@4.2.1 (lodash@4.11.0)
└── microgateway-config@2.0.10 (fs-extra@0.26.7, lodash@4.12.0)
```

Then trying to get the help message leads to an error:

```
$ edgemicro --help
current nodejs version is v4.4.3
module.js:327
    throw err;
    ^

Error: Cannot find module 'portastic'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/node-v4.4.3-linux-x64/lib/node_modules/edgemicro/cli/cmd.js:11:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by asnowfix** [comment]
BTW, same problem with `2.10-beta`:

```
npm ERR! missing: portastic@^1.0.1, required by edgemicro@2.1.0-beta
```

**Comment by asnowfix** [comment]
Going all the way back to 2.0.4 also produces the same result.

**Comment by kevinswiber** [comment]
@asnowfix Please try `edgemicro@2.1.0-beta.2` or `edgemicro@2.0.12`.  Thanks.

**Comment by asnowfix** [comment]
Works fine: talks & answers ;-)

```
$ curl http://$(docker-machine ip):8080/basepath
Error: No machine name(s) specified and no "default" machine exists.
{"message":"no match found for /basepath","status":404}
```

**Comment by asnowfix** [comment]
I tried `edgemicro@2.0.12` using Node.js LTS (a slightly modified container version).
